# Site
name: "Vespa Blog"
title: "Vespa Blog"
description: "Blog for Vespa - The open big data serving engine"
logo: 'assets/images/Vespa_Logo_Black.png'
favicon: 'assets/icons/favicon-32x32.png'
baseurl:
mailchimp-list: 'https://vespa.ai/mailing-list.html'
include: ["_pages"]
permalink: /:title/
google_analytics: UA-107187180-2
enable_featured: false

# Authors
authors:
  bjorncs:
    name: Bjørn C Seime
    display_name: Bjørn C Seime
    avatar: '/assets/avatars/bjorncs.jpg'
    email: bjorncs@verizonmedia.com
    twitter: https://twitter.com/bjorncs
    description: "Principal Vespa Engineer"
  bratseth:
    name: Jon Bratseth
    display_name: Jon Bratseth
    avatar: '/assets/avatars/bratseth.jpg'
    email: bratseth@verizonmedia.com
    twitter: https://twitter.com/jonbratseth
    description: "Vespa Chief Architect"
  geirst:
    name: Geir Storli
    display_name: Geir Storli
    avatar: '/assets/avatars/geirst.jpg'
    email: geirst@verizonmedia.com
    description: "Principal Vespa Engineer"
  kkraune:
    name: Kristian Aune
    display_name: Kristian Aune
    avatar: '/assets/avatars/kkraune.jpg'
    email: kraune@verizonmedia.com
    description: "Vespa Technical Product Manager"
  thigm85:
    name: Thiago Martins
    display_name: Thiago Martins
    avatar: '/assets/avatars/thigm85.jpg'
    email: tmartins@verizonmedia.com
    description: "Vespa Data Scientist"
  jobergum:
    name: Jo Kristian Bergum
    display_name: Jo Kristian Bergum
    avatar: '/assets/avatars/jobergum.jpg'
    email: bergum@verizonmedia.com
    description: "Vespa Solutions Architect"
  jvenstad:
    name: Jon M Venstad
    display_name: Jon M Venstad
    avatar: '/assets/avatars/jvenstad.jpg'
    email: jvenstad@verizonmedia.com
    description: "Senior Vespa Engineer"
  lesters:
    name: Lester Solbakken
    display_name: Lester Solbakken
    avatar: '/assets/avatars/lesters.jpg'
    email: lesters@verizonmedia.com
    description: "Principal Vespa Engineer"
  aressem:
    name: Arnstein Ressem
    display_name: Arnstein Ressem
    avatar: '/assets/avatars/aressem.png'
    email: aressem@verizonmedia.com
    twitter: https://twitter.com/ArnsteinRessem
    description: "Principal Software Systems Engineer"
  sujitpal:
    name: Sujit Pal
    display_name: Sujit Pal
    avatar: '/assets/avatars/sujitpal.png'
    email: sujit.pal@elsevier.com
    description: "Technology Research Director, Elsevier Labs"
  aaronnagao:
    name: Aaron Nagao
    display_name: Aaron Nagao
    avatar: '/assets/avatars/aaronnagao.jpg'
    email: aaronnagao@verizonmedia.com
    description: "Senior Software Engineer, Verizon Media"
  onorum:
    name: Ole-Magnus Vian Norum
    display_name: Ole-Magnus Vian Norum
    avatar: '/assets/avatars/onorum.jpg'
    email: ole99@live.no
    description: "Intern II, Summer of 2021"
  chunnoo:
    name: Mathias Chunnoo
    display_name: Mathias Chunnoo
    avatar: '/assets/avatars/chunnoo.jpg'
    email: mathiaschunnoo@gmail.com
    description: "Intern I, Summer of 2021"
  mortent:
    name: Morten Tokle
    display_name: Morten Tokle
    avatar: '/assets/avatars/mortent.png'
    email: mortent@verizonmedia.com
    description: "Principal Software Systems Engineer"
  vekterli:
    name: Tor Brede Vekterli
    display_name: Tor Brede Vekterli
    avatar: '/assets/avatars/vekterli.jpg'
    email: vekterli@verizonmedia.com
    description: "Principal Software Systems Engineer"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 12
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - "*/README.md"
  - Gemfile
  - Gemfile.lock
  - .idea
  - blog_index.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

search:
  namespace: "blog"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    - url: https://vespacloud-docsearch.vespa-team.aws-us-east-1c.z.vespa-app.cloud/
      indexes:
        - blog_index.json
    - url: https://vespacloud-docsearch.vespa-team.aws-ap-northeast-1a.z.vespa-app.cloud/
      indexes:
        - blog_index.json

defaults:
  -
    scope:
      path  : ""
    values:
      index : true
